---
services:
 django-web:
   build:
    dockerfile: .docker/app/Dockerfile
    context: .
   environment:
    DATABASE_HOST: db
    DATABASE_NAME: ${DATABASE_NAME}
    DATABASE_USERNAME: ${DATABASE_USERNAME}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD}
   ports:
     - "8080:8080"

 db:
   build:
    dockerfile: .docker/db/Dockerfile
    context: .
   environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
